# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20160920_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(help_text='http://example.com', unique=True, verbose_name='Original url'),
        ),
    ]
