# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(editable=False, unique=True, verbose_name='Original url')),
                ('short_url', models.TextField(verbose_name='Short url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
            options={
                'ordering': ['original_url'],
            },
        ),
    ]
